spring.application.name=shop


# Base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=${JWT_EXP_MINUTES}

# Email / SMTP
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.from=${MAIL_FROM}

# Tokens de expiración
reset-password.exp-minutes=${RESET_PASSWORD_EXP_MINUTES}
verify-email.exp-minutes=${VERIFY_EMAIL_EXP_MINUTES}

# Frontend
frontend.base-url=${FRONTEND_BASE_URL}

# Stripe
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

# Pagos
payments.provider=${PAYMENTS_PROVIDER}
